apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aerlix

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: aerlix-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: aerlix-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

images:
  - name: ghcr.io/aerlixconsulting/aerlix-regulated-delivery-control-plane/api
    newTag: latest
  - name: ghcr.io/aerlixconsulting/aerlix-regulated-delivery-control-plane/frontend
    newTag: latest

commonLabels:
  environment: production
